openapi: 3.0.1
info:
  title: '@jupiterone/graph-wpengine'
  description: A graph conversion tool for https://wpengine.com/
  x-cortex-git:
    github:
      repository: JupiterOne/graph-wpengine
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-wpengine'
